version: '3.7'
services:

  ecapim:
    # Reference : https://github.com/osixia/docker-openldap#quick-start
    image: lsflk/ecapm:latest
    container_name: ecapim
    hostname: "ecapim"
    environment:
      - DOMAIN=${DOMAIN}
    ports:
      - "10397:10397"
      - "11111:11111"
      - "5672:5672"
      - "7611:7611"
      - "7711:7711"
      - "8243:8243"
      - "8280:8280"
      - "9099:9099"
      - "9443:9443"
      - "9611:9611"
      - "9711:9711"
      - "9763:9763"
      - "9999:9999"

  authapp:
    image: lsflk/authapp
    container_name: authapp
    ports:
      - "3001:3001"
    hostname: "authapp"
    links:
      - ecapim
    depends_on:
      - ecapim

  results-tabulation-api-db:
    image: mysql:5.7.20
    ports:
      - "33306:3306"
    hostname: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - ./results-tabulation-api/.database/scripts/init:/docker-entrypoint-initdb.d
      - ./results-tabulation-api/.database/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-p123456"]
      interval: 30s
      timeout: 60s
      retries: 5
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', "--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"]

  results-tabulation-api:
    build:
      context: ./results-tabulation-api
    container_name: results-tabulation-api
    command: python index.py
    volumes:
      - ./results-tabulation-api/
    ports:
      - "5000:5000"
    environment:
      ENV_CONFIG: ./env/dev.cfg
      DEBUG: "true"
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: 123456
      DATABASE_HOST: results-tabulation-api-db
      DATABASE_PORT: 33306
      DATABASE_NAME: election
      SQLALCHEMY_POOL_SIZE: 50
      RESULT_DISSEMINATION_SYSTEM_URL: https://publishresult.ecdev.opensource.lk
      RESULT_DISSEMINATION_SYSTEM_ELECTION_CODE: 2019PRE
      RESULT_DISSEMINATION_SYSTEM_RESULT_TYPE_VOTE: PRESIDENTIAL-FIRST
      RESULT_DISSEMINATION_SYSTEM_RESULT_TYPE_PREF: PRESIDENTIAL-PREFS
      PROD_ENV: "false"
    links:
      - results-tabulation-api-db
    depends_on:
      - results-tabulation-api-db
