{
 "title": "Results Status Ballot Box District",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "elections",
    "label": "Election",
    "query": "SELECT electionName FROM election WHERE election.parentElectionId IS NULL"
   },
   {
    "name": "district",
    "label": "District",
    "query": "SELECT areaName  FROM area WHERE areaType=\"ElectoralDistrict\" and electionId=\"$electionId\" "
   },
   {
    "name": "Polling_Division",
    "label": "Polling Division",
    "query": "select DISTINCT `areaName` from area where areaType='PollingDivision' union SELECT null as `areaName`;"
   },
   {
    "name": "totalPollingStations",
    "label": "totalPollingStations",
    "query": "SELECT if(COUNT(*) is null,0,COUNT(*) ) FROM area_map WHERE electoralDIstrictId=$districtId and pollingStationId is not null;"
   },
   {
    "name": "totalRegisteredOrdinaryVoters",
    "label": "totalRegisteredOrdinaryVoters",
    "query": "SELECT SUM(pollingStation._registeredVotersCount) FROM area_map      join area as pollingStation on pollingStation.areaId = area_map.pollingStationId    WHERE electoralDistrictId = $districtId and area_map.electionId=$electionId;"
   },
   {
    "name": "totalRegisteredPostalVoters",
    "label": "totalRegisteredPostalVoters",
    "query": "select SUM(countingCentre._registeredVotersCount) from area_map join area as countingCentre on countingCentre.areaId = area_map.countingCentreId  WHERE voteType=\"Postal\" and electoralDistrictId=$districtId"
   },
   {
    "name": "districtId",
    "label": "districtId",
    "query": "SELECT areaId  FROM area WHERE areaType=\"ElectoralDistrict\" AND areaName = \"$district\" and electionId=\"$electionId\""
   },
   {
    "name": "OrdinaryCountingCentres",
    "label": "OrdinaryCountingCentres",
    "query": "SELECT COUNT(DISTINCT countingCentreId) from area_map WHERE electoralDistrictId=$districtId and voteType=\"NonPostal\";"
   },
   {
    "name": "electionId",
    "label": "electionId",
    "query": "select electionId from election where electionName = \"$elections\""
   },
   {
    "name": "PostalCountingCentres",
    "label": "PostalCountingCentres",
    "query": "SELECT COUNT(DISTINCT countingCentreId) from area_map WHERE electoralDistrictId=$districtId and voteType=\"Postal\";"
   },
   {
    "name": "totalPollingStationsPostal",
    "label": "totalPollingStationsPostal",
    "query": "SELECT COUNT(*) FROM area_map WHERE electoralDIstrictId=$districtId and voteType=\"Postal\";"
   },
   {
    "name": "OrdinaryPollingDivisions",
    "label": "OrdinaryPollingDivisions",
    "query": "SELECT COUNT(DISTINCT pollingDivisionId) from area_map WHERE electoralDistrictId=$districtId and voteType=\"NonPostal\";"
   },
   {
    "name": "totalPolledOrdinaryBallotCount",
    "label": "totalPolledOrdinaryBallotCount",
    "query": "SELECT  if(sum(ballotCount) is null,0,sum(ballotCount)) AS totalVoteCount  FROM dashboard_status_CE_201   WHERE voteType = \"Ordinary\"   AND electionId = \"$electionId\"  AND electoralDistrictId = \"$districtId\""
   },
   {
    "name": "totalPolledPostalBallotCount",
    "label": "totalPolledPostalBallotCount",
    "query": "SELECT  if(sum(ballotCount) is null,0,sum(ballotCount)) AS totalVoteCount  FROM dashboard_status_CE_201   WHERE voteType = \"Postal\"   AND electionId = \"$electionId\"  AND electoralDistrictId = \"$districtId\""
   },
   {
    "name": "districtLength",
    "label": "District",
    "query": "select LENGTH(REPLACE(\"$district\", ',', ''))"
   },
   {
    "name": "totalPolledOrdinaryBallotCountOfficial",
    "label": "totalPolledOrdinaryBallotCountOfficial",
    "query": "SELECT  if(sum(ballotCount) is null,0,sum(ballotCount)) AS totalVoteCount   FROM dashboard_status_CE_201    WHERE voteType = \"Ordinary\"    AND electionId = \"$electionId\"   AND status = \"Verified\" AND electoralDistrictId = \"$districtId\""
   },
   {
    "name": "totalPolledPostalBallotCountOfficial",
    "label": "totalPolledPostalBallotCountOfficial",
    "query": "SELECT  if(sum(ballotCount) is null,0,sum(ballotCount)) AS totalVoteCount  FROM dashboard_status_CE_201   WHERE voteType = \"Postal\"   AND electionId = \"$electionId\"  AND status = \"Verified\" AND electoralDistrictId = \"$districtId\"  "
   }
  ]
 },
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 14, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select \"$elections\"\n\n\n    \n    \n    "
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- select if($districtLength < 100,\"$district\",\"All Districts\")\nselect concat(\"Ballot Box / \",\"$district\")\n-- -- LENGTH($district) - LENGTH(REPLACE($district, ',', ''))\n\n    \n    \n    "
    }
   ]
  },
  {
   "title": "Unofficial Balllot Box Count",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "content": "\n\n\n",
   "targets": [
    {
     "rawSql": "select \"Unofficial\"\n\n    \n    \n    "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "content": "# CE - 201 (PV)\n\n\n\n\n",
   "targets": [
    {
     "rawSql": "SELECT NOW() AS time,SUM(IF(T1.registeredPostalVotersCount IS NOT NULL, T1.registeredPostalVotersCount, 0) + IF(T1.registeredOrdinaryVotersCount IS NOT NULL, T1.registeredOrdinaryVotersCount, 0))  AS value FROM (\nSELECT \n      electoralDistrict.areaName as electoralDistrictName,\n      electoralDistrict.areaId as electoralDistrictId,\n      \n      pollingDivision.areaName as pollingDivisionName,\n      pollingDivision.areaId as pollingDivisionId,\n      \n      -- pollingDistrict.areaName as pollingDistrictName,\n      -- pollingDistrict.areaId as pollingDistrictId,\n      \n      pollingStation.areaName as pollingStationName,\n\t  pollingStation.areaId as pollingStationId,\n      sum(pollingStation._registeredVotersCount) as registeredOrdinaryVotersCount,\n      \n      countingCentre.areaName as countingCentreName,\n      countingCentre.areaId as countingCentreId,\n      sum(countingCentre._registeredVotersCount) as registeredPostalVotersCount,\n      \n      countingCentreElection.voteType\n      \n      -- districtCentre.areaName as districtCentreName,\n      -- districtCentre.areaId as districtCentreId\n      \n    \n    FROM \n      area countingCentre \n      \n      left join area_area as pollingStationMapping on pollingStationMapping.parentAreaId = countingCentre.areaId\n      left join area as pollingStation on pollingStation.areaId = pollingStationMapping.childAreaId and pollingStation.areaType = \"PollingStation\"\n      \n      left join area_area as pollingDistrictMapping on pollingDistrictMapping.childAreaId = pollingStation.areaId\n      left join area as pollingDistrict on pollingDistrict.areaId = pollingDistrictMapping.parentAreaId and pollingDistrict.areaType = \"PollingDistrict\"\n      \n      left join area_area as pollingDivisionMapping on pollingDivisionMapping.childAreaId = pollingDistrict.areaId\n      left join area as pollingDivision on pollingDivision.areaId = pollingDivisionMapping.parentAreaId and pollingDivision.areaType = \"PollingDivision\"\n      \n      inner join area_area as electoralDistrictMapping on  (electoralDistrictMapping.childAreaId = pollingDivision.areaId or electoralDistrictMapping.childAreaId = countingCentre.areaId )\n      inner join area as electoralDistrict on electoralDistrict.areaId = electoralDistrictMapping.parentAreaId and electoralDistrict.areaType = \"ElectoralDistrict\"\n      \n      inner join area_area as districtCentreMapping on districtCentreMapping.childAreaId = countingCentre.areaId\n      inner join area as districtCentre on districtCentre.areaId = districtCentreMapping.parentAreaId and districtCentre.areaType = \"DistrictCentre\"\n      \n      inner join election as countingCentreElection on countingCentreElection.electionId = countingCentre.electionId\n    WHERE \n      countingCentre.areaType = \"CountingCentre\"\n      \n    GROUP BY\n      electoralDistrict.areaId,\n      pollingDivision.areaId,\n      countingCentre.areaId,\n      pollingStation.areaId\n      ) AS T1\n     WHERE T1.electoralDistrictName = \"$district\"\n     AND T1.pollingDivisionName IN ($Polling_Division)\n     OR T1.pollingDivisionName IS NULL\n\n    \n    \n    "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 5, "y": 4 },
   "content": "\n\n\n\n",
   "targets": [
    {
     "rawSql": "SELECT NOW() AS time,SUM(IF(T1.registeredPostalVotersCount IS NOT NULL, T1.registeredPostalVotersCount, 0) + IF(T1.registeredOrdinaryVotersCount IS NOT NULL, T1.registeredOrdinaryVotersCount, 0))  AS value FROM (\nSELECT \n      electoralDistrict.areaName as electoralDistrictName,\n      electoralDistrict.areaId as electoralDistrictId,\n      \n      pollingDivision.areaName as pollingDivisionName,\n      pollingDivision.areaId as pollingDivisionId,\n      \n      -- pollingDistrict.areaName as pollingDistrictName,\n      -- pollingDistrict.areaId as pollingDistrictId,\n      \n      pollingStation.areaName as pollingStationName,\n\t  pollingStation.areaId as pollingStationId,\n      sum(pollingStation._registeredVotersCount) as registeredOrdinaryVotersCount,\n      \n      countingCentre.areaName as countingCentreName,\n      countingCentre.areaId as countingCentreId,\n      sum(countingCentre._registeredVotersCount) as registeredPostalVotersCount,\n      \n      countingCentreElection.voteType\n      \n      -- districtCentre.areaName as districtCentreName,\n      -- districtCentre.areaId as districtCentreId\n      \n    \n    FROM \n      area countingCentre \n      \n      left join area_area as pollingStationMapping on pollingStationMapping.parentAreaId = countingCentre.areaId\n      left join area as pollingStation on pollingStation.areaId = pollingStationMapping.childAreaId and pollingStation.areaType = \"PollingStation\"\n      \n      left join area_area as pollingDistrictMapping on pollingDistrictMapping.childAreaId = pollingStation.areaId\n      left join area as pollingDistrict on pollingDistrict.areaId = pollingDistrictMapping.parentAreaId and pollingDistrict.areaType = \"PollingDistrict\"\n      \n      left join area_area as pollingDivisionMapping on pollingDivisionMapping.childAreaId = pollingDistrict.areaId\n      left join area as pollingDivision on pollingDivision.areaId = pollingDivisionMapping.parentAreaId and pollingDivision.areaType = \"PollingDivision\"\n      \n      inner join area_area as electoralDistrictMapping on  (electoralDistrictMapping.childAreaId = pollingDivision.areaId or electoralDistrictMapping.childAreaId = countingCentre.areaId )\n      inner join area as electoralDistrict on electoralDistrict.areaId = electoralDistrictMapping.parentAreaId and electoralDistrict.areaType = \"ElectoralDistrict\"\n      \n      inner join area_area as districtCentreMapping on districtCentreMapping.childAreaId = countingCentre.areaId\n      inner join area as districtCentre on districtCentre.areaId = districtCentreMapping.parentAreaId and districtCentre.areaType = \"DistrictCentre\"\n      \n      inner join election as countingCentreElection on countingCentreElection.electionId = countingCentre.electionId\n    WHERE \n      countingCentre.areaType = \"CountingCentre\"\n      \n    GROUP BY\n      electoralDistrict.areaId,\n      pollingDivision.areaId,\n      countingCentre.areaId,\n      pollingStation.areaId\n      ) AS T1\n     WHERE T1.electoralDistrictName = \"$district\"\n     AND T1.pollingDivisionName IN ($Polling_Division)\n     OR T1.pollingDivisionName IS NULL\n\n    \n    \n    "
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 11, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n    concat(if(completedCountingCentres is null,0,completedCountingCentres),'/',totalCountingCentres,' - ',IF(totalCountingCentres<>0 AND completedCountingCentres<>0,concat(round(( completedCountingCentres/totalCountingCentres * 100 ))),0)) AS value \n    FROM (\n    SELECT \n        $PostalCountingCentres AS totalCountingCentres,\n        SUM(IF(status = \"Submitted\" OR status = \"Entered\" OR status = \"Verified\",1,0)) AS completedCountingCentres\n    FROM (\n    SELECT \n        countingCentreId,\n        status\n    FROM dashboard_status_CE_201\n    WHERE dashboard_status_CE_201.electionId = \"$electionId\"\n    AND dashboard_status_CE_201.voteType = \"Postal\"\n    AND electoralDistrictId = $districtId\n    GROUP BY countingCentreId\n    ) AS T1\n    ) AS T2\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 4 },
   "content": "\n\n",
   "targets": [
    {
     "rawSql": "SELECT \nconcat(if(completedCountingCentres is null,0,completedCountingCentres),'/',totalCountingCentres,' - ',IF(totalCountingCentres<>0 AND completedCountingCentres<>0,concat(round(( completedCountingCentres/totalCountingCentres * 100 ))),0)) AS value \nFROM (\nSELECT \n    $PostalCountingCentres AS totalCountingCentres,\n    SUM(IF(status = \"verified\",1,0)) AS completedCountingCentres\nFROM (\n    SELECT \n    countingCentreId,\n    status\n    FROM dashboard_status_PRE_41\n    WHERE electionId = \"$electionId\"\n    AND voteType = \"Postal\"\n    AND electoralDistrictId = \"$districtId\"\n    GROUP BY countingCentreId\n  ) AS counting_centre_wise_status\n) AS T1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "content": "# CE - 201 \n\n\n\n\n",
   "targets": [
    {
     "rawSql": "SELECT NOW() AS time,SUM(IF(T1.registeredPostalVotersCount IS NOT NULL, T1.registeredPostalVotersCount, 0) + IF(T1.registeredOrdinaryVotersCount IS NOT NULL, T1.registeredOrdinaryVotersCount, 0))  AS value FROM (\nSELECT \n      electoralDistrict.areaName as electoralDistrictName,\n      electoralDistrict.areaId as electoralDistrictId,\n      \n      pollingDivision.areaName as pollingDivisionName,\n      pollingDivision.areaId as pollingDivisionId,\n      \n      -- pollingDistrict.areaName as pollingDistrictName,\n      -- pollingDistrict.areaId as pollingDistrictId,\n      \n      pollingStation.areaName as pollingStationName,\n\t  pollingStation.areaId as pollingStationId,\n      sum(pollingStation._registeredVotersCount) as registeredOrdinaryVotersCount,\n      \n      countingCentre.areaName as countingCentreName,\n      countingCentre.areaId as countingCentreId,\n      sum(countingCentre._registeredVotersCount) as registeredPostalVotersCount,\n      \n      countingCentreElection.voteType\n      \n      -- districtCentre.areaName as districtCentreName,\n      -- districtCentre.areaId as districtCentreId\n      \n    \n    FROM \n      area countingCentre \n      \n      left join area_area as pollingStationMapping on pollingStationMapping.parentAreaId = countingCentre.areaId\n      left join area as pollingStation on pollingStation.areaId = pollingStationMapping.childAreaId and pollingStation.areaType = \"PollingStation\"\n      \n      left join area_area as pollingDistrictMapping on pollingDistrictMapping.childAreaId = pollingStation.areaId\n      left join area as pollingDistrict on pollingDistrict.areaId = pollingDistrictMapping.parentAreaId and pollingDistrict.areaType = \"PollingDistrict\"\n      \n      left join area_area as pollingDivisionMapping on pollingDivisionMapping.childAreaId = pollingDistrict.areaId\n      left join area as pollingDivision on pollingDivision.areaId = pollingDivisionMapping.parentAreaId and pollingDivision.areaType = \"PollingDivision\"\n      \n      inner join area_area as electoralDistrictMapping on  (electoralDistrictMapping.childAreaId = pollingDivision.areaId or electoralDistrictMapping.childAreaId = countingCentre.areaId )\n      inner join area as electoralDistrict on electoralDistrict.areaId = electoralDistrictMapping.parentAreaId and electoralDistrict.areaType = \"ElectoralDistrict\"\n      \n      inner join area_area as districtCentreMapping on districtCentreMapping.childAreaId = countingCentre.areaId\n      inner join area as districtCentre on districtCentre.areaId = districtCentreMapping.parentAreaId and districtCentre.areaType = \"DistrictCentre\"\n      \n      inner join election as countingCentreElection on countingCentreElection.electionId = countingCentre.electionId\n    WHERE \n      countingCentre.areaType = \"CountingCentre\"\n      \n    GROUP BY\n      electoralDistrict.areaId,\n      pollingDivision.areaId,\n      countingCentre.areaId,\n      pollingStation.areaId\n      ) AS T1\n     WHERE T1.electoralDistrictName = \"$district\"\n     AND T1.pollingDivisionName IN ($Polling_Division)\n     OR T1.pollingDivisionName IS NULL\n\n    \n    \n    "
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- SELECT \n--     concat(completedPollingStations,'/',totalPollingStations,' - ',IF(totalPollingStations<>0 AND completedPollingStations<>0,concat(round(( completedPollingStations/totalPollingStations * 100 ))),0)) AS value FROM (\n--     SELECT \n--         COUNT(DISTINCT pollingStation) AS totalPollingStations,\n--         SUM(IF(status = \"verrified\",1,0)) AS completedPollingStations\n--     FROM dashboard_status_CE_201\n--     WHERE electionName = \"$elections\"\n--     AND electoralDistrict = \"$district\"\n--     AND voteType = \"Ordinary\"\n--     ) AS T1\nSELECT \n    concat(if(completedPollingStations is null,0,completedPollingStations),'/',totalPollingStations,' - ',IF(totalPollingStations<>0 AND completedPollingStations<>0,concat(round(( completedPollingStations/totalPollingStations * 100 ))),0)) AS value FROM (\n    SELECT \n        $totalPollingStations AS totalPollingStations,\n        SUM(IF(status = \"Submitted\" OR status = \"Entered\" OR status = \"Verified\",1,0)) AS completedPollingStations\n    FROM dashboard_status_CE_201\n    WHERE electionId = \"$electionId\"\n    AND voteType = \"Ordinary\" AND electoralDistrictId = $districtId\n    ) AS T1\n"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 11, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n    concat(if(completedCountingCentres is null,0,completedCountingCentres),'/',totalCountingCentres,' - ',IF(totalCountingCentres<>0 AND completedCountingCentres<>0,concat(round(( completedCountingCentres/totalCountingCentres * 100 ))),0)) AS value \n    FROM (\n    SELECT \n        $OrdinaryCountingCentres AS totalCountingCentres,\n        SUM(IF(status = \"Submitted\" OR status = \"Entered\" OR status = \"Verified\",1,0)) AS completedCountingCentres\n    FROM (\n    SELECT \n        countingCentreId,\n        status\n    FROM dashboard_status_CE_201\n    WHERE electionId = \"$electionId\"\n    AND electoralDistrictId = \"$districtId\"\n    AND voteType = \"Ordinary\"\n    GROUP BY countingCentreId\n    ) AS T1\n    ) AS T2\n\n"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- SELECT \n--     concat(if(completedPollingDivisions is null,0,completedPollingDivisions),'/',totalPollingDivisions,' - ',IF(totalPollingDivisions<>0 AND completedPollingDivisions<>0,concat(round(( completedPollingDivisions/totalPollingDivisions * 100 ))),0)) AS value \n--     FROM (\n--     SELECT \n--         $OrdinaryPollingDivisions AS totalPollingDivisions,\n--         SUM(IF(totalCountingCentres=completedCountingCentres,1,0)) AS completedPollingDivisions\n--         FROM (\n--         SELECT \n--         $OrdinaryCountingCentres AS totalCountingCentres,\n--         SUM(IF(status = \"Verified\",1,0)) AS completedCountingCentres\n--     FROM (\n--     SELECT \n--         countingCentreId,\n--         status\n--         FROM dashboard_status_CE_201\n--     WHERE electionId = \"$electionId\"\n--     AND voteType = \"Ordinary\"\n--     AND electoralDistrictId = \"$districtId\"\n--     GROUP BY countingCentreId\n--     ) AS T1\n--     ) AS T2\n--     ) AS T3\n\n\nSELECT\n      concat(if(completedPollingDivisions is null,0,completedPollingDivisions),'/',$OrdinaryPollingDivisions,' - ',IF($OrdinaryPollingDivisions<>0 AND completedPollingDivisions<>0,concat(round(( completedPollingDivisions/$OrdinaryPollingDivisions * 100 ))),0)) AS value \nFROM\n  (\n    SELECT\n      SUM(IF(notCompletedCountingCentres = 0, 1, 0)) as completedPollingDivisions\n    FROM\n      (\n        SELECT \n          pollingDivision.*,\n          SUM(IF(status = \"Submitted\" OR status = \"Entered\" OR status = \"Verified\",0,1)) as notCompletedCountingCentres\n        FROM \n          dashboard_status_CE_201\n          join area_map on area_map.countingCentreId = dashboard_status_CE_201.countingCentreId\n          join area as pollingDivision on pollingDivision.areaId = area_map.pollingDivisionId\n        WHERE \n          dashboard_status_CE_201.electionId = \"$electionId\"\n          AND dashboard_status_CE_201.voteType = \"Ordinary\"\n          AND dashboard_status_CE_201.electoralDistrictId = \"$districtId\"\n        GROUP BY\n          area_map.pollingDivisionId\n      ) as pollingDivision201Status\n    ) as pollingDivision201Summary"
    }
   ]
  },
  {
   "title": "Official Ballot Box Count",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "content": "\n\n",
   "targets": [
    {
     "rawSql": "-- select sum(($totalPolledValidOrdinaryVotes + $totalPolledValidPostalVotes + $totalPolledRejectedPostalVotes + $totalPolledRejectedOrdinaryVotes)/($totalRegisteredOrdinaryVoters + $totalRegisteredPostalVoters) * 100)\n SELECT IF(sum($totalPolledValidOrdinaryVotes + $totalPolledValidPostalVotes + $totalPolledRejectedPostalVotes + $totalPolledRejectedOrdinaryVotes)<>0 AND sum($totalRegisteredOrdinaryVoters + $totalRegisteredPostalVoters)<>0,\n          (round(( ($totalPolledValidOrdinaryVotes + $totalPolledValidPostalVotes + $totalPolledRejectedPostalVotes + $totalPolledRejectedOrdinaryVotes)/($totalRegisteredOrdinaryVoters + $totalRegisteredPostalVoters) * 100 ))),0) AS percentage \n\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 9 },
   "content": "# CE - 201 (PV)\n\n\n\n\n",
   "targets": [
    {
     "rawSql": "SELECT NOW() AS time,SUM(IF(T1.registeredPostalVotersCount IS NOT NULL, T1.registeredPostalVotersCount, 0) + IF(T1.registeredOrdinaryVotersCount IS NOT NULL, T1.registeredOrdinaryVotersCount, 0))  AS value FROM (\nSELECT \n      electoralDistrict.areaName as electoralDistrictName,\n      electoralDistrict.areaId as electoralDistrictId,\n      \n      pollingDivision.areaName as pollingDivisionName,\n      pollingDivision.areaId as pollingDivisionId,\n      \n      -- pollingDistrict.areaName as pollingDistrictName,\n      -- pollingDistrict.areaId as pollingDistrictId,\n      \n      pollingStation.areaName as pollingStationName,\n\t  pollingStation.areaId as pollingStationId,\n      sum(pollingStation._registeredVotersCount) as registeredOrdinaryVotersCount,\n      \n      countingCentre.areaName as countingCentreName,\n      countingCentre.areaId as countingCentreId,\n      sum(countingCentre._registeredVotersCount) as registeredPostalVotersCount,\n      \n      countingCentreElection.voteType\n      \n      -- districtCentre.areaName as districtCentreName,\n      -- districtCentre.areaId as districtCentreId\n      \n    \n    FROM \n      area countingCentre \n      \n      left join area_area as pollingStationMapping on pollingStationMapping.parentAreaId = countingCentre.areaId\n      left join area as pollingStation on pollingStation.areaId = pollingStationMapping.childAreaId and pollingStation.areaType = \"PollingStation\"\n      \n      left join area_area as pollingDistrictMapping on pollingDistrictMapping.childAreaId = pollingStation.areaId\n      left join area as pollingDistrict on pollingDistrict.areaId = pollingDistrictMapping.parentAreaId and pollingDistrict.areaType = \"PollingDistrict\"\n      \n      left join area_area as pollingDivisionMapping on pollingDivisionMapping.childAreaId = pollingDistrict.areaId\n      left join area as pollingDivision on pollingDivision.areaId = pollingDivisionMapping.parentAreaId and pollingDivision.areaType = \"PollingDivision\"\n      \n      inner join area_area as electoralDistrictMapping on  (electoralDistrictMapping.childAreaId = pollingDivision.areaId or electoralDistrictMapping.childAreaId = countingCentre.areaId )\n      inner join area as electoralDistrict on electoralDistrict.areaId = electoralDistrictMapping.parentAreaId and electoralDistrict.areaType = \"ElectoralDistrict\"\n      \n      inner join area_area as districtCentreMapping on districtCentreMapping.childAreaId = countingCentre.areaId\n      inner join area as districtCentre on districtCentre.areaId = districtCentreMapping.parentAreaId and districtCentre.areaType = \"DistrictCentre\"\n      \n      inner join election as countingCentreElection on countingCentreElection.electionId = countingCentre.electionId\n    WHERE \n      countingCentre.areaType = \"CountingCentre\"\n      \n    GROUP BY\n      electoralDistrict.areaId,\n      pollingDivision.areaId,\n      countingCentre.areaId,\n      pollingStation.areaId\n      ) AS T1\n     WHERE T1.electoralDistrictName = \"$district\"\n     AND T1.pollingDivisionName IN ($Polling_Division)\n     OR T1.pollingDivisionName IS NULL\n\n    \n    \n    "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 9 },
   "content": "\n\n\n\n",
   "targets": [
    {
     "rawSql": "SELECT NOW() AS time,SUM(IF(T1.registeredPostalVotersCount IS NOT NULL, T1.registeredPostalVotersCount, 0) + IF(T1.registeredOrdinaryVotersCount IS NOT NULL, T1.registeredOrdinaryVotersCount, 0))  AS value FROM (\nSELECT \n      electoralDistrict.areaName as electoralDistrictName,\n      electoralDistrict.areaId as electoralDistrictId,\n      \n      pollingDivision.areaName as pollingDivisionName,\n      pollingDivision.areaId as pollingDivisionId,\n      \n      -- pollingDistrict.areaName as pollingDistrictName,\n      -- pollingDistrict.areaId as pollingDistrictId,\n      \n      pollingStation.areaName as pollingStationName,\n\t  pollingStation.areaId as pollingStationId,\n      sum(pollingStation._registeredVotersCount) as registeredOrdinaryVotersCount,\n      \n      countingCentre.areaName as countingCentreName,\n      countingCentre.areaId as countingCentreId,\n      sum(countingCentre._registeredVotersCount) as registeredPostalVotersCount,\n      \n      countingCentreElection.voteType\n      \n      -- districtCentre.areaName as districtCentreName,\n      -- districtCentre.areaId as districtCentreId\n      \n    \n    FROM \n      area countingCentre \n      \n      left join area_area as pollingStationMapping on pollingStationMapping.parentAreaId = countingCentre.areaId\n      left join area as pollingStation on pollingStation.areaId = pollingStationMapping.childAreaId and pollingStation.areaType = \"PollingStation\"\n      \n      left join area_area as pollingDistrictMapping on pollingDistrictMapping.childAreaId = pollingStation.areaId\n      left join area as pollingDistrict on pollingDistrict.areaId = pollingDistrictMapping.parentAreaId and pollingDistrict.areaType = \"PollingDistrict\"\n      \n      left join area_area as pollingDivisionMapping on pollingDivisionMapping.childAreaId = pollingDistrict.areaId\n      left join area as pollingDivision on pollingDivision.areaId = pollingDivisionMapping.parentAreaId and pollingDivision.areaType = \"PollingDivision\"\n      \n      inner join area_area as electoralDistrictMapping on  (electoralDistrictMapping.childAreaId = pollingDivision.areaId or electoralDistrictMapping.childAreaId = countingCentre.areaId )\n      inner join area as electoralDistrict on electoralDistrict.areaId = electoralDistrictMapping.parentAreaId and electoralDistrict.areaType = \"ElectoralDistrict\"\n      \n      inner join area_area as districtCentreMapping on districtCentreMapping.childAreaId = countingCentre.areaId\n      inner join area as districtCentre on districtCentre.areaId = districtCentreMapping.parentAreaId and districtCentre.areaType = \"DistrictCentre\"\n      \n      inner join election as countingCentreElection on countingCentreElection.electionId = countingCentre.electionId\n    WHERE \n      countingCentre.areaType = \"CountingCentre\"\n      \n    GROUP BY\n      electoralDistrict.areaId,\n      pollingDivision.areaId,\n      countingCentre.areaId,\n      pollingStation.areaId\n      ) AS T1\n     WHERE T1.electoralDistrictName = \"$district\"\n     AND T1.pollingDivisionName IN ($Polling_Division)\n     OR T1.pollingDivisionName IS NULL\n\n    \n    \n    "
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 11, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n    concat(if(completedCountingCentres is null,0,completedCountingCentres),'/',totalCountingCentres,' - ',IF(totalCountingCentres<>0 AND completedCountingCentres<>0,concat(round(( completedCountingCentres/totalCountingCentres * 100 ))),0)) AS value \n    FROM (\n    SELECT \n        $PostalCountingCentres AS totalCountingCentres,\n        SUM(IF(status = \"Verified\",1,0)) AS completedCountingCentres\n    FROM (\n    SELECT \n        countingCentreId,\n        status\n    FROM dashboard_status_CE_201\n    WHERE electionId = \"$electionId\"\n    AND voteType = \"Postal\"\n    AND electoralDistrictId in (\"$districtId\")\n    GROUP BY countingCentreId\n    ) AS T1\n    ) AS T2"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 9 },
   "content": "\n\n",
   "targets": [
    {
     "rawSql": "SELECT \nconcat(if(completedCountingCentres is null,0,completedCountingCentres),'/',totalCountingCentres,' - ',IF(totalCountingCentres<>0 AND completedCountingCentres<>0,concat(round(( completedCountingCentres/totalCountingCentres * 100 ))),0)) AS value \nFROM (\nSELECT \n    $PostalCountingCentres AS totalCountingCentres,\n    SUM(IF(status = \"verified\",1,0)) AS completedCountingCentres\nFROM (\n    SELECT \n    countingCentreId,\n    status\n    FROM dashboard_status_PRE_41\n    WHERE electionId = \"$electionId\"\n    AND voteType = \"Postal\"\n    AND electoralDistrictId = \"$districtId\"\n    GROUP BY countingCentreId\n  ) AS counting_centre_wise_status\n) AS T1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 11 },
   "content": "# CE - 201 \n\n\n\n\n",
   "targets": [
    {
     "rawSql": "SELECT NOW() AS time,SUM(IF(T1.registeredPostalVotersCount IS NOT NULL, T1.registeredPostalVotersCount, 0) + IF(T1.registeredOrdinaryVotersCount IS NOT NULL, T1.registeredOrdinaryVotersCount, 0))  AS value FROM (\nSELECT \n      electoralDistrict.areaName as electoralDistrictName,\n      electoralDistrict.areaId as electoralDistrictId,\n      \n      pollingDivision.areaName as pollingDivisionName,\n      pollingDivision.areaId as pollingDivisionId,\n      \n      -- pollingDistrict.areaName as pollingDistrictName,\n      -- pollingDistrict.areaId as pollingDistrictId,\n      \n      pollingStation.areaName as pollingStationName,\n\t  pollingStation.areaId as pollingStationId,\n      sum(pollingStation._registeredVotersCount) as registeredOrdinaryVotersCount,\n      \n      countingCentre.areaName as countingCentreName,\n      countingCentre.areaId as countingCentreId,\n      sum(countingCentre._registeredVotersCount) as registeredPostalVotersCount,\n      \n      countingCentreElection.voteType\n      \n      -- districtCentre.areaName as districtCentreName,\n      -- districtCentre.areaId as districtCentreId\n      \n    \n    FROM \n      area countingCentre \n      \n      left join area_area as pollingStationMapping on pollingStationMapping.parentAreaId = countingCentre.areaId\n      left join area as pollingStation on pollingStation.areaId = pollingStationMapping.childAreaId and pollingStation.areaType = \"PollingStation\"\n      \n      left join area_area as pollingDistrictMapping on pollingDistrictMapping.childAreaId = pollingStation.areaId\n      left join area as pollingDistrict on pollingDistrict.areaId = pollingDistrictMapping.parentAreaId and pollingDistrict.areaType = \"PollingDistrict\"\n      \n      left join area_area as pollingDivisionMapping on pollingDivisionMapping.childAreaId = pollingDistrict.areaId\n      left join area as pollingDivision on pollingDivision.areaId = pollingDivisionMapping.parentAreaId and pollingDivision.areaType = \"PollingDivision\"\n      \n      inner join area_area as electoralDistrictMapping on  (electoralDistrictMapping.childAreaId = pollingDivision.areaId or electoralDistrictMapping.childAreaId = countingCentre.areaId )\n      inner join area as electoralDistrict on electoralDistrict.areaId = electoralDistrictMapping.parentAreaId and electoralDistrict.areaType = \"ElectoralDistrict\"\n      \n      inner join area_area as districtCentreMapping on districtCentreMapping.childAreaId = countingCentre.areaId\n      inner join area as districtCentre on districtCentre.areaId = districtCentreMapping.parentAreaId and districtCentre.areaType = \"DistrictCentre\"\n      \n      inner join election as countingCentreElection on countingCentreElection.electionId = countingCentre.electionId\n    WHERE \n      countingCentre.areaType = \"CountingCentre\"\n      \n    GROUP BY\n      electoralDistrict.areaId,\n      pollingDivision.areaId,\n      countingCentre.areaId,\n      pollingStation.areaId\n      ) AS T1\n     WHERE T1.electoralDistrictName = \"$district\"\n     AND T1.pollingDivisionName IN ($Polling_Division)\n     OR T1.pollingDivisionName IS NULL\n\n    \n    \n    "
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 4, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- SELECT \n--     concat(completedPollingStations,'/',totalPollingStations,' - ',IF(totalPollingStations<>0 AND completedPollingStations<>0,concat(round(( completedPollingStations/totalPollingStations * 100 ))),0)) AS value FROM (\n--     SELECT \n--         COUNT(DISTINCT pollingStation) AS totalPollingStations,\n--         SUM(IF(status = \"verrified\",1,0)) AS completedPollingStations\n--     FROM dashboard_status_CE_201\n--     WHERE electionName = \"$elections\"\n--     AND electoralDistrict = \"$district\"\n--     AND voteType = \"Ordinary\"\n--     ) AS T1\nSELECT \n    concat(if(completedPollingStations is null,0,completedPollingStations),'/',totalPollingStations,' - ',IF(totalPollingStations<>0 AND completedPollingStations<>0,concat(round(( completedPollingStations/totalPollingStations * 100 ))),0)) AS value FROM (\n    SELECT \n        $totalPollingStations AS totalPollingStations,\n        SUM(IF(status = \"Verified\",1,0)) AS completedPollingStations\n    FROM dashboard_status_CE_201\n    WHERE electionId = \"$electionId\"\n    AND voteType = \"Ordinary\" AND electoralDistrictId = $districtId\n    ) AS T1\n"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 11, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n    concat(if(completedCountingCentres is null,0,completedCountingCentres),'/',totalCountingCentres,' - ',IF(totalCountingCentres<>0 AND completedCountingCentres<>0,concat(round(( completedCountingCentres/totalCountingCentres * 100 ))),0)) AS value \n    FROM (\n    SELECT \n        $OrdinaryCountingCentres AS totalCountingCentres,\n        SUM(IF(status = \"Verified\",1,0)) AS completedCountingCentres\n    FROM (\n    SELECT \n        countingCentreId,\n        status\n    FROM dashboard_status_CE_201\n    WHERE electionId = \"$electionId\"\n    AND electoralDistrictId = \"$districtId\"\n    AND voteType = \"Ordinary\"\n    GROUP BY countingCentreId\n    ) AS T1\n    ) AS T2\n\n"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- SELECT \n--     concat(if(completedPollingDivisions is null,0,completedPollingDivisions),'/',totalPollingDivisions,' - ',IF(totalPollingDivisions<>0 AND completedPollingDivisions<>0,concat(round(( completedPollingDivisions/totalPollingDivisions * 100 ))),0)) AS value \n--     FROM (\n--     SELECT \n--         $OrdinaryPollingDivisions AS totalPollingDivisions,\n--         SUM(IF(totalCountingCentres=completedCountingCentres,1,0)) AS completedPollingDivisions\n--         FROM (\n--         SELECT \n--         $OrdinaryCountingCentres AS totalCountingCentres,\n--         SUM(IF(status = \"Verified\",1,0)) AS completedCountingCentres\n--     FROM (\n--     SELECT \n--         countingCentreId,\n--         status\n--         FROM dashboard_status_CE_201\n--     WHERE electionId = \"$electionId\"\n--     AND voteType = \"Ordinary\"\n--     AND electoralDistrictId = \"$districtId\"\n--     GROUP BY countingCentreId\n--     ) AS T1\n--     ) AS T2\n--     ) AS T3\n\n\nSELECT\n      concat(if(completedPollingDivisions is null,0,completedPollingDivisions),'/',$OrdinaryPollingDivisions,' - ',IF($OrdinaryPollingDivisions<>0 AND completedPollingDivisions<>0,concat(round(( completedPollingDivisions/$OrdinaryPollingDivisions * 100 ))),0)) AS value \nFROM\n  (\n    SELECT\n      SUM(IF(notCompletedCountingCentres = 0, 1, 0)) as completedPollingDivisions\n    FROM\n      (\n        SELECT \n          pollingDivision.*,\n          SUM(IF(status = \"Verified\",0,1)) as notCompletedCountingCentres\n        FROM \n          dashboard_status_CE_201\n          join area_map on area_map.countingCentreId = dashboard_status_CE_201.countingCentreId\n          join area as pollingDivision on pollingDivision.areaId = area_map.pollingDivisionId\n        WHERE \n          dashboard_status_CE_201.electionId = \"$electionId\"\n          AND dashboard_status_CE_201.voteType = \"Ordinary\"\n          AND dashboard_status_CE_201.electoralDistrictId = \"$districtId\"\n        GROUP BY\n          area_map.pollingDivisionId\n      ) as pollingDivision201Status\n    ) as pollingDivision201Summary"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 13 },
   "content": "# \n\n\n\n\n",
   "targets": [
    {
     "rawSql": "SELECT NOW() AS time,SUM(IF(T1.registeredPostalVotersCount IS NOT NULL, T1.registeredPostalVotersCount, 0) + IF(T1.registeredOrdinaryVotersCount IS NOT NULL, T1.registeredOrdinaryVotersCount, 0))  AS value FROM (\nSELECT \n      electoralDistrict.areaName as electoralDistrictName,\n      electoralDistrict.areaId as electoralDistrictId,\n      \n      pollingDivision.areaName as pollingDivisionName,\n      pollingDivision.areaId as pollingDivisionId,\n      \n      -- pollingDistrict.areaName as pollingDistrictName,\n      -- pollingDistrict.areaId as pollingDistrictId,\n      \n      pollingStation.areaName as pollingStationName,\n\t  pollingStation.areaId as pollingStationId,\n      sum(pollingStation._registeredVotersCount) as registeredOrdinaryVotersCount,\n      \n      countingCentre.areaName as countingCentreName,\n      countingCentre.areaId as countingCentreId,\n      sum(countingCentre._registeredVotersCount) as registeredPostalVotersCount,\n      \n      countingCentreElection.voteType\n      \n      -- districtCentre.areaName as districtCentreName,\n      -- districtCentre.areaId as districtCentreId\n      \n    \n    FROM \n      area countingCentre \n      \n      left join area_area as pollingStationMapping on pollingStationMapping.parentAreaId = countingCentre.areaId\n      left join area as pollingStation on pollingStation.areaId = pollingStationMapping.childAreaId and pollingStation.areaType = \"PollingStation\"\n      \n      left join area_area as pollingDistrictMapping on pollingDistrictMapping.childAreaId = pollingStation.areaId\n      left join area as pollingDistrict on pollingDistrict.areaId = pollingDistrictMapping.parentAreaId and pollingDistrict.areaType = \"PollingDistrict\"\n      \n      left join area_area as pollingDivisionMapping on pollingDivisionMapping.childAreaId = pollingDistrict.areaId\n      left join area as pollingDivision on pollingDivision.areaId = pollingDivisionMapping.parentAreaId and pollingDivision.areaType = \"PollingDivision\"\n      \n      inner join area_area as electoralDistrictMapping on  (electoralDistrictMapping.childAreaId = pollingDivision.areaId or electoralDistrictMapping.childAreaId = countingCentre.areaId )\n      inner join area as electoralDistrict on electoralDistrict.areaId = electoralDistrictMapping.parentAreaId and electoralDistrict.areaType = \"ElectoralDistrict\"\n      \n      inner join area_area as districtCentreMapping on districtCentreMapping.childAreaId = countingCentre.areaId\n      inner join area as districtCentre on districtCentre.areaId = districtCentreMapping.parentAreaId and districtCentre.areaType = \"DistrictCentre\"\n      \n      inner join election as countingCentreElection on countingCentreElection.electionId = countingCentre.electionId\n    WHERE \n      countingCentre.areaType = \"CountingCentre\"\n      \n    GROUP BY\n      electoralDistrict.areaId,\n      pollingDivision.areaId,\n      countingCentre.areaId,\n      pollingStation.areaId\n      ) AS T1\n     WHERE T1.electoralDistrictName = \"$district\"\n     AND T1.pollingDivisionName IN ($Polling_Division)\n     OR T1.pollingDivisionName IS NULL\n\n    \n    \n    "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 4, "y": 13 },
   "content": "# Non Postal\n\n\n\n\n",
   "targets": [
    {
     "rawSql": "SELECT NOW() AS time,SUM(IF(T1.registeredPostalVotersCount IS NOT NULL, T1.registeredPostalVotersCount, 0) + IF(T1.registeredOrdinaryVotersCount IS NOT NULL, T1.registeredOrdinaryVotersCount, 0))  AS value FROM (\nSELECT \n      electoralDistrict.areaName as electoralDistrictName,\n      electoralDistrict.areaId as electoralDistrictId,\n      \n      pollingDivision.areaName as pollingDivisionName,\n      pollingDivision.areaId as pollingDivisionId,\n      \n      -- pollingDistrict.areaName as pollingDistrictName,\n      -- pollingDistrict.areaId as pollingDistrictId,\n      \n      pollingStation.areaName as pollingStationName,\n\t  pollingStation.areaId as pollingStationId,\n      sum(pollingStation._registeredVotersCount) as registeredOrdinaryVotersCount,\n      \n      countingCentre.areaName as countingCentreName,\n      countingCentre.areaId as countingCentreId,\n      sum(countingCentre._registeredVotersCount) as registeredPostalVotersCount,\n      \n      countingCentreElection.voteType\n      \n      -- districtCentre.areaName as districtCentreName,\n      -- districtCentre.areaId as districtCentreId\n      \n    \n    FROM \n      area countingCentre \n      \n      left join area_area as pollingStationMapping on pollingStationMapping.parentAreaId = countingCentre.areaId\n      left join area as pollingStation on pollingStation.areaId = pollingStationMapping.childAreaId and pollingStation.areaType = \"PollingStation\"\n      \n      left join area_area as pollingDistrictMapping on pollingDistrictMapping.childAreaId = pollingStation.areaId\n      left join area as pollingDistrict on pollingDistrict.areaId = pollingDistrictMapping.parentAreaId and pollingDistrict.areaType = \"PollingDistrict\"\n      \n      left join area_area as pollingDivisionMapping on pollingDivisionMapping.childAreaId = pollingDistrict.areaId\n      left join area as pollingDivision on pollingDivision.areaId = pollingDivisionMapping.parentAreaId and pollingDivision.areaType = \"PollingDivision\"\n      \n      inner join area_area as electoralDistrictMapping on  (electoralDistrictMapping.childAreaId = pollingDivision.areaId or electoralDistrictMapping.childAreaId = countingCentre.areaId )\n      inner join area as electoralDistrict on electoralDistrict.areaId = electoralDistrictMapping.parentAreaId and electoralDistrict.areaType = \"ElectoralDistrict\"\n      \n      inner join area_area as districtCentreMapping on districtCentreMapping.childAreaId = countingCentre.areaId\n      inner join area as districtCentre on districtCentre.areaId = districtCentreMapping.parentAreaId and districtCentre.areaType = \"DistrictCentre\"\n      \n      inner join election as countingCentreElection on countingCentreElection.electionId = countingCentre.electionId\n    WHERE \n      countingCentre.areaType = \"CountingCentre\"\n      \n    GROUP BY\n      electoralDistrict.areaId,\n      pollingDivision.areaId,\n      countingCentre.areaId,\n      pollingStation.areaId\n      ) AS T1\n     WHERE T1.electoralDistrictName = \"$district\"\n     AND T1.pollingDivisionName IN ($Polling_Division)\n     OR T1.pollingDivisionName IS NULL\n\n    \n    \n    "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 11, "y": 13 },
   "content": "# Postal\n\n\n\n\n",
   "targets": [
    {
     "rawSql": "SELECT NOW() AS time,SUM(IF(T1.registeredPostalVotersCount IS NOT NULL, T1.registeredPostalVotersCount, 0) + IF(T1.registeredOrdinaryVotersCount IS NOT NULL, T1.registeredOrdinaryVotersCount, 0))  AS value FROM (\nSELECT \n      electoralDistrict.areaName as electoralDistrictName,\n      electoralDistrict.areaId as electoralDistrictId,\n      \n      pollingDivision.areaName as pollingDivisionName,\n      pollingDivision.areaId as pollingDivisionId,\n      \n      -- pollingDistrict.areaName as pollingDistrictName,\n      -- pollingDistrict.areaId as pollingDistrictId,\n      \n      pollingStation.areaName as pollingStationName,\n\t  pollingStation.areaId as pollingStationId,\n      sum(pollingStation._registeredVotersCount) as registeredOrdinaryVotersCount,\n      \n      countingCentre.areaName as countingCentreName,\n      countingCentre.areaId as countingCentreId,\n      sum(countingCentre._registeredVotersCount) as registeredPostalVotersCount,\n      \n      countingCentreElection.voteType\n      \n      -- districtCentre.areaName as districtCentreName,\n      -- districtCentre.areaId as districtCentreId\n      \n    \n    FROM \n      area countingCentre \n      \n      left join area_area as pollingStationMapping on pollingStationMapping.parentAreaId = countingCentre.areaId\n      left join area as pollingStation on pollingStation.areaId = pollingStationMapping.childAreaId and pollingStation.areaType = \"PollingStation\"\n      \n      left join area_area as pollingDistrictMapping on pollingDistrictMapping.childAreaId = pollingStation.areaId\n      left join area as pollingDistrict on pollingDistrict.areaId = pollingDistrictMapping.parentAreaId and pollingDistrict.areaType = \"PollingDistrict\"\n      \n      left join area_area as pollingDivisionMapping on pollingDivisionMapping.childAreaId = pollingDistrict.areaId\n      left join area as pollingDivision on pollingDivision.areaId = pollingDivisionMapping.parentAreaId and pollingDivision.areaType = \"PollingDivision\"\n      \n      inner join area_area as electoralDistrictMapping on  (electoralDistrictMapping.childAreaId = pollingDivision.areaId or electoralDistrictMapping.childAreaId = countingCentre.areaId )\n      inner join area as electoralDistrict on electoralDistrict.areaId = electoralDistrictMapping.parentAreaId and electoralDistrict.areaType = \"ElectoralDistrict\"\n      \n      inner join area_area as districtCentreMapping on districtCentreMapping.childAreaId = countingCentre.areaId\n      inner join area as districtCentre on districtCentre.areaId = districtCentreMapping.parentAreaId and districtCentre.areaType = \"DistrictCentre\"\n      \n      inner join election as countingCentreElection on countingCentreElection.electionId = countingCentre.electionId\n    WHERE \n      countingCentre.areaType = \"CountingCentre\"\n      \n    GROUP BY\n      electoralDistrict.areaId,\n      pollingDivision.areaId,\n      countingCentre.areaId,\n      pollingStation.areaId\n      ) AS T1\n     WHERE T1.electoralDistrictName = \"$district\"\n     AND T1.pollingDivisionName IN ($Polling_Division)\n     OR T1.pollingDivisionName IS NULL\n\n    \n    \n    "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 13 },
   "content": "# Total\n\n\n\n\n",
   "targets": [
    {
     "rawSql": "SELECT NOW() AS time,SUM(IF(T1.registeredPostalVotersCount IS NOT NULL, T1.registeredPostalVotersCount, 0) + IF(T1.registeredOrdinaryVotersCount IS NOT NULL, T1.registeredOrdinaryVotersCount, 0))  AS value FROM (\nSELECT \n      electoralDistrict.areaName as electoralDistrictName,\n      electoralDistrict.areaId as electoralDistrictId,\n      \n      pollingDivision.areaName as pollingDivisionName,\n      pollingDivision.areaId as pollingDivisionId,\n      \n      -- pollingDistrict.areaName as pollingDistrictName,\n      -- pollingDistrict.areaId as pollingDistrictId,\n      \n      pollingStation.areaName as pollingStationName,\n\t  pollingStation.areaId as pollingStationId,\n      sum(pollingStation._registeredVotersCount) as registeredOrdinaryVotersCount,\n      \n      countingCentre.areaName as countingCentreName,\n      countingCentre.areaId as countingCentreId,\n      sum(countingCentre._registeredVotersCount) as registeredPostalVotersCount,\n      \n      countingCentreElection.voteType\n      \n      -- districtCentre.areaName as districtCentreName,\n      -- districtCentre.areaId as districtCentreId\n      \n    \n    FROM \n      area countingCentre \n      \n      left join area_area as pollingStationMapping on pollingStationMapping.parentAreaId = countingCentre.areaId\n      left join area as pollingStation on pollingStation.areaId = pollingStationMapping.childAreaId and pollingStation.areaType = \"PollingStation\"\n      \n      left join area_area as pollingDistrictMapping on pollingDistrictMapping.childAreaId = pollingStation.areaId\n      left join area as pollingDistrict on pollingDistrict.areaId = pollingDistrictMapping.parentAreaId and pollingDistrict.areaType = \"PollingDistrict\"\n      \n      left join area_area as pollingDivisionMapping on pollingDivisionMapping.childAreaId = pollingDistrict.areaId\n      left join area as pollingDivision on pollingDivision.areaId = pollingDivisionMapping.parentAreaId and pollingDivision.areaType = \"PollingDivision\"\n      \n      inner join area_area as electoralDistrictMapping on  (electoralDistrictMapping.childAreaId = pollingDivision.areaId or electoralDistrictMapping.childAreaId = countingCentre.areaId )\n      inner join area as electoralDistrict on electoralDistrict.areaId = electoralDistrictMapping.parentAreaId and electoralDistrict.areaType = \"ElectoralDistrict\"\n      \n      inner join area_area as districtCentreMapping on districtCentreMapping.childAreaId = countingCentre.areaId\n      inner join area as districtCentre on districtCentre.areaId = districtCentreMapping.parentAreaId and districtCentre.areaType = \"DistrictCentre\"\n      \n      inner join election as countingCentreElection on countingCentreElection.electionId = countingCentre.electionId\n    WHERE \n      countingCentre.areaType = \"CountingCentre\"\n      \n    GROUP BY\n      electoralDistrict.areaId,\n      pollingDivision.areaId,\n      countingCentre.areaId,\n      pollingStation.areaId\n      ) AS T1\n     WHERE T1.electoralDistrictName = \"$district\"\n     AND T1.pollingDivisionName IN ($Polling_Division)\n     OR T1.pollingDivisionName IS NULL\n\n    \n    \n    "
    }
   ]
  },
  {
   "title": "Unofficial Ballot Box Count",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "content": "\n\n",
   "targets": [
    {
     "rawSql": "-- SELECT IF(totalRegisteredPostalVotes<>0 AND totalVoteCount<>0,concat(round(( totalVoteCount/totalRegisteredPostalVotes * 100 ))),0) AS percentage FROM(\n-- SELECT SUM(\n--         IF(pre_cc_wise_rejected_vote_count.rejectedVoteCount IS NOT NULL, pre_cc_wise_rejected_vote_count.rejectedVoteCount, 0) + \n--         IF(pre_cc_wise_valid_vote_count.validVoteCount IS NOT NULL, pre_cc_wise_valid_vote_count.validVoteCount, 0)\n--     ) AS totalVoteCount,\n--     SUM(IF(registered_postal_non_postal_votes_view.registeredPostalVotersCount IS NOT NULL,registered_postal_non_postal_votes_view.registeredPostalVotersCount,0)) AS totalRegisteredPostalVotes\n-- FROM \n--   pre_cc_wise_rejected_vote_count \n--   INNER JOIN pre_cc_wise_valid_vote_count ON\n--       pre_cc_wise_rejected_vote_count.countingCentreId=pre_cc_wise_valid_vote_count.countingCentreId\n-- \tINNER JOIN registered_postal_non_postal_votes_view ON\n--       pre_cc_wise_valid_vote_count.countingCentreId = registered_postal_non_postal_votes_view.countingCentreId\n--       WHERE pre_cc_wise_valid_vote_count.electionId=1\n--       and pre_cc_wise_rejected_vote_count.electoralDistrictName  = \"$district\"\n--       and pre_cc_wise_valid_vote_count.voteType = \"Postal\"\n-- ) AS T1\n  SELECT IF($totalRegisteredPostalVoters<>0 AND ($totalPolledValidPostalVotes + $totalPolledRejectedPostalVotes)<>0,concat(round(( ($totalPolledValidPostalVotes + $totalPolledRejectedPostalVotes)/$totalRegisteredPostalVoters * 100 ))),0) AS percentage \n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 16 },
   "content": "# Electors\n\n\n\n\n",
   "targets": [
    {
     "rawSql": "SELECT NOW() AS time,SUM(IF(T1.registeredPostalVotersCount IS NOT NULL, T1.registeredPostalVotersCount, 0) + IF(T1.registeredOrdinaryVotersCount IS NOT NULL, T1.registeredOrdinaryVotersCount, 0))  AS value FROM (\nSELECT \n      electoralDistrict.areaName as electoralDistrictName,\n      electoralDistrict.areaId as electoralDistrictId,\n      \n      pollingDivision.areaName as pollingDivisionName,\n      pollingDivision.areaId as pollingDivisionId,\n      \n      -- pollingDistrict.areaName as pollingDistrictName,\n      -- pollingDistrict.areaId as pollingDistrictId,\n      \n      pollingStation.areaName as pollingStationName,\n\t  pollingStation.areaId as pollingStationId,\n      sum(pollingStation._registeredVotersCount) as registeredOrdinaryVotersCount,\n      \n      countingCentre.areaName as countingCentreName,\n      countingCentre.areaId as countingCentreId,\n      sum(countingCentre._registeredVotersCount) as registeredPostalVotersCount,\n      \n      countingCentreElection.voteType\n      \n      -- districtCentre.areaName as districtCentreName,\n      -- districtCentre.areaId as districtCentreId\n      \n    \n    FROM \n      area countingCentre \n      \n      left join area_area as pollingStationMapping on pollingStationMapping.parentAreaId = countingCentre.areaId\n      left join area as pollingStation on pollingStation.areaId = pollingStationMapping.childAreaId and pollingStation.areaType = \"PollingStation\"\n      \n      left join area_area as pollingDistrictMapping on pollingDistrictMapping.childAreaId = pollingStation.areaId\n      left join area as pollingDistrict on pollingDistrict.areaId = pollingDistrictMapping.parentAreaId and pollingDistrict.areaType = \"PollingDistrict\"\n      \n      left join area_area as pollingDivisionMapping on pollingDivisionMapping.childAreaId = pollingDistrict.areaId\n      left join area as pollingDivision on pollingDivision.areaId = pollingDivisionMapping.parentAreaId and pollingDivision.areaType = \"PollingDivision\"\n      \n      inner join area_area as electoralDistrictMapping on  (electoralDistrictMapping.childAreaId = pollingDivision.areaId or electoralDistrictMapping.childAreaId = countingCentre.areaId )\n      inner join area as electoralDistrict on electoralDistrict.areaId = electoralDistrictMapping.parentAreaId and electoralDistrict.areaType = \"ElectoralDistrict\"\n      \n      inner join area_area as districtCentreMapping on districtCentreMapping.childAreaId = countingCentre.areaId\n      inner join area as districtCentre on districtCentre.areaId = districtCentreMapping.parentAreaId and districtCentre.areaType = \"DistrictCentre\"\n      \n      inner join election as countingCentreElection on countingCentreElection.electionId = countingCentre.electionId\n    WHERE \n      countingCentre.areaType = \"CountingCentre\"\n      \n    GROUP BY\n      electoralDistrict.areaId,\n      pollingDivision.areaId,\n      countingCentre.areaId,\n      pollingStation.areaId\n      ) AS T1\n     WHERE T1.electoralDistrictName = \"$district\"\n     AND T1.pollingDivisionName IN ($Polling_Division)\n     OR T1.pollingDivisionName IS NULL\n\n    \n    \n    "
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 4, "y": 16 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- SELECT SUM(pollingStation._registeredVotersCount) FROM area_map \n-- join area as pollingStation on pollingStation.areaId = area_map.pollingStationId \n-- WHERE electoralDistrictId in ($districtId) and area_map.electionId=$electionId;\n\nselect $totalRegisteredOrdinaryVoters\n\n    \n    \n    "
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 11, "y": 16 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select $totalRegisteredPostalVoters as val\n\n-- select SUM(countingCentre._registeredVotersCount) from area_map join area as countingCentre on countingCentre.areaId = area_map.countingCentreId \n-- WHERE voteType=\"Postal\" and electoralDistrictId=$districtId"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 16 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select $totalRegisteredOrdinaryVoters + $totalRegisteredPostalVoters\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 18 },
   "content": "# Polled\n\n\n\n\n",
   "targets": [
    {
     "rawSql": "SELECT NOW() AS time,SUM(IF(T1.registeredPostalVotersCount IS NOT NULL, T1.registeredPostalVotersCount, 0) + IF(T1.registeredOrdinaryVotersCount IS NOT NULL, T1.registeredOrdinaryVotersCount, 0))  AS value FROM (\nSELECT \n      electoralDistrict.areaName as electoralDistrictName,\n      electoralDistrict.areaId as electoralDistrictId,\n      \n      pollingDivision.areaName as pollingDivisionName,\n      pollingDivision.areaId as pollingDivisionId,\n      \n      -- pollingDistrict.areaName as pollingDistrictName,\n      -- pollingDistrict.areaId as pollingDistrictId,\n      \n      pollingStation.areaName as pollingStationName,\n\t  pollingStation.areaId as pollingStationId,\n      sum(pollingStation._registeredVotersCount) as registeredOrdinaryVotersCount,\n      \n      countingCentre.areaName as countingCentreName,\n      countingCentre.areaId as countingCentreId,\n      sum(countingCentre._registeredVotersCount) as registeredPostalVotersCount,\n      \n      countingCentreElection.voteType\n      \n      -- districtCentre.areaName as districtCentreName,\n      -- districtCentre.areaId as districtCentreId\n      \n    \n    FROM \n      area countingCentre \n      \n      left join area_area as pollingStationMapping on pollingStationMapping.parentAreaId = countingCentre.areaId\n      left join area as pollingStation on pollingStation.areaId = pollingStationMapping.childAreaId and pollingStation.areaType = \"PollingStation\"\n      \n      left join area_area as pollingDistrictMapping on pollingDistrictMapping.childAreaId = pollingStation.areaId\n      left join area as pollingDistrict on pollingDistrict.areaId = pollingDistrictMapping.parentAreaId and pollingDistrict.areaType = \"PollingDistrict\"\n      \n      left join area_area as pollingDivisionMapping on pollingDivisionMapping.childAreaId = pollingDistrict.areaId\n      left join area as pollingDivision on pollingDivision.areaId = pollingDivisionMapping.parentAreaId and pollingDivision.areaType = \"PollingDivision\"\n      \n      inner join area_area as electoralDistrictMapping on  (electoralDistrictMapping.childAreaId = pollingDivision.areaId or electoralDistrictMapping.childAreaId = countingCentre.areaId )\n      inner join area as electoralDistrict on electoralDistrict.areaId = electoralDistrictMapping.parentAreaId and electoralDistrict.areaType = \"ElectoralDistrict\"\n      \n      inner join area_area as districtCentreMapping on districtCentreMapping.childAreaId = countingCentre.areaId\n      inner join area as districtCentre on districtCentre.areaId = districtCentreMapping.parentAreaId and districtCentre.areaType = \"DistrictCentre\"\n      \n      inner join election as countingCentreElection on countingCentreElection.electionId = countingCentre.electionId\n    WHERE \n      countingCentre.areaType = \"CountingCentre\"\n      \n    GROUP BY\n      electoralDistrict.areaId,\n      pollingDivision.areaId,\n      countingCentre.areaId,\n      pollingStation.areaId\n      ) AS T1\n     WHERE T1.electoralDistrictName = \"$district\"\n     AND T1.pollingDivisionName IN ($Polling_Division)\n     OR T1.pollingDivisionName IS NULL\n\n    \n    \n    "
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 4, "y": 18 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- SELECT  if(sum(ballotCount) is null,0,sum(ballotCount)) AS totalVoteCount \n-- FROM dashboard_status_CE_201  \n-- WHERE voteType = \"Ordinary\"  \n-- AND electionId = \"$electionId\" \n-- -- AND (status=\"Submitted\" OR status=\"Entered\" OR status=\"Verified\")\n-- AND electoralDistrictId = \"$districtId\"  \nselect $totalPolledOrdinaryBallotCount"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 11, "y": 18 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- SELECT  if(sum(ballotCount) is null,0,sum(ballotCount)) AS totalVoteCount \n-- FROM dashboard_status_CE_201  \n-- WHERE voteType = \"Postal\"  \n-- AND electionId = \"$electionId\" \n-- AND electoralDistrictId IN ($districtId)  \nselect $totalPolledPostalBallotCount \n"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 18 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": " select $totalPolledOrdinaryBallotCount + $totalPolledPostalBallotCount   \n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 20 },
   "content": "# %\n\n\n\n\n",
   "targets": [
    {
     "rawSql": "SELECT NOW() AS time,SUM(IF(T1.registeredPostalVotersCount IS NOT NULL, T1.registeredPostalVotersCount, 0) + IF(T1.registeredOrdinaryVotersCount IS NOT NULL, T1.registeredOrdinaryVotersCount, 0))  AS value FROM (\nSELECT \n      electoralDistrict.areaName as electoralDistrictName,\n      electoralDistrict.areaId as electoralDistrictId,\n      \n      pollingDivision.areaName as pollingDivisionName,\n      pollingDivision.areaId as pollingDivisionId,\n      \n      -- pollingDistrict.areaName as pollingDistrictName,\n      -- pollingDistrict.areaId as pollingDistrictId,\n      \n      pollingStation.areaName as pollingStationName,\n\t  pollingStation.areaId as pollingStationId,\n      sum(pollingStation._registeredVotersCount) as registeredOrdinaryVotersCount,\n      \n      countingCentre.areaName as countingCentreName,\n      countingCentre.areaId as countingCentreId,\n      sum(countingCentre._registeredVotersCount) as registeredPostalVotersCount,\n      \n      countingCentreElection.voteType\n      \n      -- districtCentre.areaName as districtCentreName,\n      -- districtCentre.areaId as districtCentreId\n      \n    \n    FROM \n      area countingCentre \n      \n      left join area_area as pollingStationMapping on pollingStationMapping.parentAreaId = countingCentre.areaId\n      left join area as pollingStation on pollingStation.areaId = pollingStationMapping.childAreaId and pollingStation.areaType = \"PollingStation\"\n      \n      left join area_area as pollingDistrictMapping on pollingDistrictMapping.childAreaId = pollingStation.areaId\n      left join area as pollingDistrict on pollingDistrict.areaId = pollingDistrictMapping.parentAreaId and pollingDistrict.areaType = \"PollingDistrict\"\n      \n      left join area_area as pollingDivisionMapping on pollingDivisionMapping.childAreaId = pollingDistrict.areaId\n      left join area as pollingDivision on pollingDivision.areaId = pollingDivisionMapping.parentAreaId and pollingDivision.areaType = \"PollingDivision\"\n      \n      inner join area_area as electoralDistrictMapping on  (electoralDistrictMapping.childAreaId = pollingDivision.areaId or electoralDistrictMapping.childAreaId = countingCentre.areaId )\n      inner join area as electoralDistrict on electoralDistrict.areaId = electoralDistrictMapping.parentAreaId and electoralDistrict.areaType = \"ElectoralDistrict\"\n      \n      inner join area_area as districtCentreMapping on districtCentreMapping.childAreaId = countingCentre.areaId\n      inner join area as districtCentre on districtCentre.areaId = districtCentreMapping.parentAreaId and districtCentre.areaType = \"DistrictCentre\"\n      \n      inner join election as countingCentreElection on countingCentreElection.electionId = countingCentre.electionId\n    WHERE \n      countingCentre.areaType = \"CountingCentre\"\n      \n    GROUP BY\n      electoralDistrict.areaId,\n      pollingDivision.areaId,\n      countingCentre.areaId,\n      pollingStation.areaId\n      ) AS T1\n     WHERE T1.electoralDistrictName = \"$district\"\n     AND T1.pollingDivisionName IN ($Polling_Division)\n     OR T1.pollingDivisionName IS NULL\n\n    \n    \n    "
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 4, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "\nSELECT IF($totalRegisteredOrdinaryVoters<>0 AND ($totalPolledOrdinaryBallotCount)<>0,concat(round(( ($totalPolledOrdinaryBallotCount)/$totalRegisteredOrdinaryVoters * 100 ))),0) AS percentage \n"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 11, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "\n  SELECT IF($totalRegisteredPostalVoters<>0 AND ($totalPolledPostalBallotCount)<>0,concat(round(( ($totalPolledPostalBallotCount)/$totalRegisteredPostalVoters * 100 ))),0) AS percentage \n"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- select sum(($totalPolledValidOrdinaryVotes + $totalPolledValidPostalVotes + $totalPolledRejectedPostalVotes + $totalPolledRejectedOrdinaryVotes)/($totalRegisteredOrdinaryVoters + $totalRegisteredPostalVoters) * 100)\n SELECT IF(sum($totalPolledOrdinaryBallotCount + $totalPolledPostalBallotCount )<>0 AND sum($totalRegisteredOrdinaryVoters + $totalRegisteredPostalVoters)<>0,\n          (round(( ($totalPolledOrdinaryBallotCount + $totalPolledPostalBallotCount)/($totalRegisteredOrdinaryVoters + $totalRegisteredPostalVoters) * 100 ))),0) AS percentage \n\n"
    }
   ]
  },
  {
   "title": "Official Ballot Box Count",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "content": "\n\n",
   "targets": [
    {
     "rawSql": "-- SELECT IF(totalRegisteredPostalVotes<>0 AND totalVoteCount<>0,concat(round(( totalVoteCount/totalRegisteredPostalVotes * 100 ))),0) AS percentage FROM(\n-- SELECT SUM(\n--         IF(pre_cc_wise_rejected_vote_count.rejectedVoteCount IS NOT NULL, pre_cc_wise_rejected_vote_count.rejectedVoteCount, 0) + \n--         IF(pre_cc_wise_valid_vote_count.validVoteCount IS NOT NULL, pre_cc_wise_valid_vote_count.validVoteCount, 0)\n--     ) AS totalVoteCount,\n--     SUM(IF(registered_postal_non_postal_votes_view.registeredPostalVotersCount IS NOT NULL,registered_postal_non_postal_votes_view.registeredPostalVotersCount,0)) AS totalRegisteredPostalVotes\n-- FROM \n--   pre_cc_wise_rejected_vote_count \n--   INNER JOIN pre_cc_wise_valid_vote_count ON\n--       pre_cc_wise_rejected_vote_count.countingCentreId=pre_cc_wise_valid_vote_count.countingCentreId\n-- \tINNER JOIN registered_postal_non_postal_votes_view ON\n--       pre_cc_wise_valid_vote_count.countingCentreId = registered_postal_non_postal_votes_view.countingCentreId\n--       WHERE pre_cc_wise_valid_vote_count.electionId=1\n--       and pre_cc_wise_rejected_vote_count.electoralDistrictName  = \"$district\"\n--       and pre_cc_wise_valid_vote_count.voteType = \"Postal\"\n-- ) AS T1\n  SELECT IF($totalRegisteredPostalVoters<>0 AND ($totalPolledValidPostalVotes + $totalPolledRejectedPostalVotes)<>0,concat(round(( ($totalPolledValidPostalVotes + $totalPolledRejectedPostalVotes)/$totalRegisteredPostalVoters * 100 ))),0) AS percentage \n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 23 },
   "content": "# Polled\n\n\n\n\n",
   "targets": [
    {
     "rawSql": "SELECT NOW() AS time,SUM(IF(T1.registeredPostalVotersCount IS NOT NULL, T1.registeredPostalVotersCount, 0) + IF(T1.registeredOrdinaryVotersCount IS NOT NULL, T1.registeredOrdinaryVotersCount, 0))  AS value FROM (\nSELECT \n      electoralDistrict.areaName as electoralDistrictName,\n      electoralDistrict.areaId as electoralDistrictId,\n      \n      pollingDivision.areaName as pollingDivisionName,\n      pollingDivision.areaId as pollingDivisionId,\n      \n      -- pollingDistrict.areaName as pollingDistrictName,\n      -- pollingDistrict.areaId as pollingDistrictId,\n      \n      pollingStation.areaName as pollingStationName,\n\t  pollingStation.areaId as pollingStationId,\n      sum(pollingStation._registeredVotersCount) as registeredOrdinaryVotersCount,\n      \n      countingCentre.areaName as countingCentreName,\n      countingCentre.areaId as countingCentreId,\n      sum(countingCentre._registeredVotersCount) as registeredPostalVotersCount,\n      \n      countingCentreElection.voteType\n      \n      -- districtCentre.areaName as districtCentreName,\n      -- districtCentre.areaId as districtCentreId\n      \n    \n    FROM \n      area countingCentre \n      \n      left join area_area as pollingStationMapping on pollingStationMapping.parentAreaId = countingCentre.areaId\n      left join area as pollingStation on pollingStation.areaId = pollingStationMapping.childAreaId and pollingStation.areaType = \"PollingStation\"\n      \n      left join area_area as pollingDistrictMapping on pollingDistrictMapping.childAreaId = pollingStation.areaId\n      left join area as pollingDistrict on pollingDistrict.areaId = pollingDistrictMapping.parentAreaId and pollingDistrict.areaType = \"PollingDistrict\"\n      \n      left join area_area as pollingDivisionMapping on pollingDivisionMapping.childAreaId = pollingDistrict.areaId\n      left join area as pollingDivision on pollingDivision.areaId = pollingDivisionMapping.parentAreaId and pollingDivision.areaType = \"PollingDivision\"\n      \n      inner join area_area as electoralDistrictMapping on  (electoralDistrictMapping.childAreaId = pollingDivision.areaId or electoralDistrictMapping.childAreaId = countingCentre.areaId )\n      inner join area as electoralDistrict on electoralDistrict.areaId = electoralDistrictMapping.parentAreaId and electoralDistrict.areaType = \"ElectoralDistrict\"\n      \n      inner join area_area as districtCentreMapping on districtCentreMapping.childAreaId = countingCentre.areaId\n      inner join area as districtCentre on districtCentre.areaId = districtCentreMapping.parentAreaId and districtCentre.areaType = \"DistrictCentre\"\n      \n      inner join election as countingCentreElection on countingCentreElection.electionId = countingCentre.electionId\n    WHERE \n      countingCentre.areaType = \"CountingCentre\"\n      \n    GROUP BY\n      electoralDistrict.areaId,\n      pollingDivision.areaId,\n      countingCentre.areaId,\n      pollingStation.areaId\n      ) AS T1\n     WHERE T1.electoralDistrictName = \"$district\"\n     AND T1.pollingDivisionName IN ($Polling_Division)\n     OR T1.pollingDivisionName IS NULL\n\n    \n    \n    "
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 4, "y": 23 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- SELECT  if(sum(ballotCount) is null,0,sum(ballotCount)) AS totalVoteCount  \n-- FROM dashboard_status_CE_201   \n-- WHERE voteType = \"Ordinary\"   \n-- AND electionId = \"$electionId\"  \n-- AND status = \"Verified\"\n-- AND electoralDistrictId = \"$districtId\"\n\nselect $totalPolledOrdinaryBallotCountOfficial\n"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 11, "y": 23 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- SELECT  if(sum(ballotCount) is null,0,sum(ballotCount)) AS totalVoteCount \n-- FROM dashboard_status_CE_201  \n-- WHERE voteType = \"Postal\"  \n-- AND electionId = \"$electionId\" \n-- AND status = \"Verified\"\n-- AND electoralDistrictId = \"$districtId\"  \nselect $totalPolledPostalBallotCountOfficial \n"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 23 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": " select $totalPolledOrdinaryBallotCountOfficial + $totalPolledPostalBallotCountOfficial \n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 25 },
   "content": "# %\n\n\n\n\n",
   "targets": [
    {
     "rawSql": "SELECT NOW() AS time,SUM(IF(T1.registeredPostalVotersCount IS NOT NULL, T1.registeredPostalVotersCount, 0) + IF(T1.registeredOrdinaryVotersCount IS NOT NULL, T1.registeredOrdinaryVotersCount, 0))  AS value FROM (\nSELECT \n      electoralDistrict.areaName as electoralDistrictName,\n      electoralDistrict.areaId as electoralDistrictId,\n      \n      pollingDivision.areaName as pollingDivisionName,\n      pollingDivision.areaId as pollingDivisionId,\n      \n      -- pollingDistrict.areaName as pollingDistrictName,\n      -- pollingDistrict.areaId as pollingDistrictId,\n      \n      pollingStation.areaName as pollingStationName,\n\t  pollingStation.areaId as pollingStationId,\n      sum(pollingStation._registeredVotersCount) as registeredOrdinaryVotersCount,\n      \n      countingCentre.areaName as countingCentreName,\n      countingCentre.areaId as countingCentreId,\n      sum(countingCentre._registeredVotersCount) as registeredPostalVotersCount,\n      \n      countingCentreElection.voteType\n      \n      -- districtCentre.areaName as districtCentreName,\n      -- districtCentre.areaId as districtCentreId\n      \n    \n    FROM \n      area countingCentre \n      \n      left join area_area as pollingStationMapping on pollingStationMapping.parentAreaId = countingCentre.areaId\n      left join area as pollingStation on pollingStation.areaId = pollingStationMapping.childAreaId and pollingStation.areaType = \"PollingStation\"\n      \n      left join area_area as pollingDistrictMapping on pollingDistrictMapping.childAreaId = pollingStation.areaId\n      left join area as pollingDistrict on pollingDistrict.areaId = pollingDistrictMapping.parentAreaId and pollingDistrict.areaType = \"PollingDistrict\"\n      \n      left join area_area as pollingDivisionMapping on pollingDivisionMapping.childAreaId = pollingDistrict.areaId\n      left join area as pollingDivision on pollingDivision.areaId = pollingDivisionMapping.parentAreaId and pollingDivision.areaType = \"PollingDivision\"\n      \n      inner join area_area as electoralDistrictMapping on  (electoralDistrictMapping.childAreaId = pollingDivision.areaId or electoralDistrictMapping.childAreaId = countingCentre.areaId )\n      inner join area as electoralDistrict on electoralDistrict.areaId = electoralDistrictMapping.parentAreaId and electoralDistrict.areaType = \"ElectoralDistrict\"\n      \n      inner join area_area as districtCentreMapping on districtCentreMapping.childAreaId = countingCentre.areaId\n      inner join area as districtCentre on districtCentre.areaId = districtCentreMapping.parentAreaId and districtCentre.areaType = \"DistrictCentre\"\n      \n      inner join election as countingCentreElection on countingCentreElection.electionId = countingCentre.electionId\n    WHERE \n      countingCentre.areaType = \"CountingCentre\"\n      \n    GROUP BY\n      electoralDistrict.areaId,\n      pollingDivision.areaId,\n      countingCentre.areaId,\n      pollingStation.areaId\n      ) AS T1\n     WHERE T1.electoralDistrictName = \"$district\"\n     AND T1.pollingDivisionName IN ($Polling_Division)\n     OR T1.pollingDivisionName IS NULL\n\n    \n    \n    "
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 4, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "\nSELECT IF($totalRegisteredOrdinaryVoters<>0 AND ($totalPolledOrdinaryBallotCountOfficial)<>0,concat(round(( ($totalPolledOrdinaryBallotCountOfficial)/$totalRegisteredOrdinaryVoters * 100 ))),0) AS percentage \n"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 11, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "\n  SELECT IF($totalRegisteredPostalVoters<>0 AND ($totalPolledPostalBallotCountOfficial)<>0,concat(round(( ($totalPolledPostalBallotCountOfficial)/$totalRegisteredPostalVoters * 100 ))),0) AS percentage \n"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- select sum(($totalPolledValidOrdinaryVotes + $totalPolledValidPostalVotes + $totalPolledRejectedPostalVotes + $totalPolledRejectedOrdinaryVotes)/($totalRegisteredOrdinaryVoters + $totalRegisteredPostalVoters) * 100)\n SELECT IF(sum($totalPolledOrdinaryBallotCountOfficial + $totalPolledPostalBallotCountOfficial)<>0 AND sum($totalRegisteredOrdinaryVoters + $totalRegisteredPostalVoters)<>0,\n          (round(( ($totalPolledOrdinaryBallotCountOfficial + $totalPolledPostalBallotCountOfficial)/($totalRegisteredOrdinaryVoters + $totalRegisteredPostalVoters) * 100 ))),0) AS percentage \n\n"
    }
   ]
  }
 ]
}