name: Platformer Generated dbu-dev-master-push Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on:
      - ubuntu-latest
    env:
      SERVICE_NAME: ghcr.io/eclk/results-tabulation
      CONTAINER_REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: event-version
        run: echo ::set-output
          name=SOURCE_TAG::${GITHUB_REF#refs/heads/}-${{github.sha}}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker build --tag
          ${SERVICE_NAME}:update-${{steps.event-version.outputs.SOURCE_TAG }} --file
          ./results-tabulation-dashboard/Dockerfile
          ./results-tabulation-dashboard/
      - name: GitHub Image Push
        run: docker push $SERVICE_NAME:update-${{steps.event-version.outputs.SOURCE_TAG }}
      - name: Platformer Deploy
        uses: platformer-com/build-deploy-action@v1
        with:
          org-id: ${{secrets.ORG_ID_9CBA253F_B6ED_4CD0_B890_70A3810F0633}}
          project-id: ${{secrets.PROJECT_ID_9CBA253F_B6ED_4CD0_B890_70A3810F0633}}
          token: ${{secrets.AUTOGENERATED_CICD_9CBA253F_B6ED_4CD0_B890_70A3810F0633}}
          image-name: ${{env.SERVICE_NAME}}
          tag: update-${{steps.event-version.outputs.SOURCE_TAG }}
          container-id: b852a116-f1eb-4800-80fb-47ba926442eb
