name: Platformer Generated ui-stag-push Build
'on':
  push:
    tags:
      - stag*
jobs:
  build:
    runs-on:
      - ubuntu-latest
    env:
      SERVICE_NAME: ghcr.io/eclk/results-tabulation
      CONTAINER_REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: event-version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD_9F99429F_1443_4FB8_9AFA_8B3A9D362E90 }}
      - name: Build the Docker image
        run: docker build --tag ${SERVICE_NAME}:${{steps.event-version.outputs.SOURCE_TAG }} --file ./results-tabulation-ui/Dockerfile ./results-tabulation-ui/ --build-arg AUTH_APP_URL="https://tabulations.ecstage.opensource.lk" --build-arg TABULATION_API_URL="https://apim-gw.ecstag.opensource.lk/tabulation/0.1.0"
      - name: GitHub Image Push
        run: docker push $SERVICE_NAME:${{steps.event-version.outputs.SOURCE_TAG }}
      - name: Platformer Deploy
        uses: platformer-com/build-deploy-action@v1
        with:
          org-id: ${{secrets.ORG_ID_FCB1AEBE_71DB_4911_9067_F5FA9BA73D4D}}
          project-id: ${{secrets.PROJECT_ID_FCB1AEBE_71DB_4911_9067_F5FA9BA73D4D}}
          token: ${{secrets.AUTOGENERATED_CICD_FCB1AEBE_71DB_4911_9067_F5FA9BA73D4D}}
          image-name: ${{env.SERVICE_NAME}}
          tag: ${{steps.event-version.outputs.SOURCE_TAG }}
          container-id: 38522196-e2fb-453e-9729-2aac6c203042
