name: Platformer Generated stag-api-tag-push Build
on:
  push:
    tags:
      - stag-*
jobs:
  build:
    runs-on:
      - ubuntu-latest
    env:
      SERVICE_NAME: ghcr.io/eclk/results-tabulation
      CONTAINER_REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: event-version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker build --tag
          ${SERVICE_NAME}:${{steps.event-version.outputs.SOURCE_TAG }} --file
          ./results-tabulation-api/Dockerfile ./results-tabulation-api/
      - name: GitHub Image Push
        run: docker push $SERVICE_NAME:${{steps.event-version.outputs.SOURCE_TAG }}
      - name: Platformer Deploy
        uses: platformer-com/build-deploy-action@v1
        with:
          org-id: ${{secrets.ORG_ID_BCBDC02D_6FBA_4B10_9603_D19453632123}}
          project-id: ${{secrets.PROJECT_ID_BCBDC02D_6FBA_4B10_9603_D19453632123}}
          token: ${{secrets.AUTOGENERATED_CICD_BCBDC02D_6FBA_4B10_9603_D19453632123}}
          image-name: ${{env.SERVICE_NAME}}
          tag: ${{steps.event-version.outputs.SOURCE_TAG }}
          container-id: 017c3bee-7f08-49fd-b82a-f4b6f3504eee
